### ISSUE TITLE
Error in download.file(url, destfile, quiet = TRUE) : 

### ISSUE THREAD

**Issue by MamushChu** [wh90999/ChIAPoP#2]
Hello! I am analyzing data using ChIAPOP with the following script. 
`pop.pipeline("K562_1.fastq", "K562_2.fastq","hg19.bowtie/hg19")`
and got the following error:

```
Error in download.file(url, destfile, quiet = TRUE) : 
 Can't open URL'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz'
Warning message:
In download.file(url, destfile, quiet = TRUE) :
  URL 'http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz': status was 'Couldn't resolve host name'
```
Therefore, would you please give me some hint how I can solve it. 

Thank you!

**Comment by niuleon** [comment]
It seems that the function cannot find the bowtie index. You can try to replace the "hg19.bowtie/hg19" by the full path to your bowtie index.
 
Please let me know if it works

**Comment by MamushChu** [comment]
Thank you dear Professor.
It is working.
